In [ ]:
#Import relevant packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Import drive and mount, import csv and save to df
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/CS-215/Data/prof-W-B-location-edited.csv')

#Inspect df
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Unnamed: 0.1,Unnamed: 0,lat,lon,timestamp,datetime,time_delta,distance_Olin
0,1,909779,39.739592,-105.161785,2022-03-09 12:02:03.803000+00:00,2022-03-09 12:02:03.803000+00:00,0 days 00:00:59.597000,1279.600701
1,2,909780,39.767084,-105.142443,2022-03-09 12:04:04.224000+00:00,2022-03-09 12:04:04.224000+00:00,0 days 00:02:00.421000,1279.046263
2,3,909781,39.784075,-105.135851,2022-03-09 12:05:03.769000+00:00,2022-03-09 12:05:03.769000+00:00,0 days 00:00:59.545000,1278.344000
3,4,909782,39.784501,-105.085261,2022-03-09 12:07:21.803000+00:00,2022-03-09 12:07:21.803000+00:00,0 days 00:02:18.034000,1281.746995
4,5,909783,39.784735,-105.063591,2022-03-09 12:08:21.830000+00:00,2022-03-09 12:08:21.830000+00:00,0 days 00:01:00.027000,1283.202415
...,...,...,...,...,...,...,...,...
1613,1614,911392,39.786299,-104.811715,2022-03-12 22:01:34.597000+00:00,2022-03-12 22:01:34.597000+00:00,0 days 00:00:33.481000,1300.248459
1614,1615,911393,39.786206,-104.811759,2022-03-12 22:02:06.613000+00:00,2022-03-12 22:02:06.613000+00:00,0 days 00:00:32.016000,1300.251709
1615,1616,911394,39.785963,-104.811527,2022-03-12 22:02:42.434000+00:00,2022-03-12 22:02:42.434000+00:00,0 days 00:00:35.821000,1300.283733
1616,1617,911395,39.786378,-104.811420,2022-03-12 22:03:14.305000+00:00,2022-03-12 22:03:14.305000+00:00,0 days 00:00:31.871000,1300.263328
1617,1618,911396,39.785948,-104.811264,2022-03-12 22:03:50.655000+00:00,2022-03-12 22:03:50.655000+00:00,0 days 00:00:36.350000,1300.302705

In [ ]:
#Select relative location, my house at 715 Estrella St
phi = [46.074203, -118.3272895]

#Import Haversine formula
!pip install haversine
from haversine import haversine, Unit

#function to iterate through df
def ndf(df):
  # Apply haversine distance calculation row-wise
  df['distance_phi'] = df.apply(lambda row: haversine(phi, (row['lat'], row['lon']), unit=Unit.KILOMETERS), axis=1)
  return df
ndf(df)
df

Requirement already satisfied: haversine in /usr/local/lib/python3.12/dist-packages (2.9.0)

,Unnamed: 0.1,Unnamed: 0,lat,lon,timestamp,datetime,time_delta,distance_Olin,distance_phi
0,1,909779,39.739592,-105.161785,2022-03-09 12:02:03.803000+00:00,2022-03-09 12:02:03.803000+00:00,0 days 00:00:59.597000,1279.600701,1280.378866
1,2,909780,39.767084,-105.142443,2022-03-09 12:04:04.224000+00:00,2022-03-09 12:04:04.224000+00:00,0 days 00:02:00.421000,1279.046263,1279.823620
2,3,909781,39.784075,-105.135851,2022-03-09 12:05:03.769000+00:00,2022-03-09 12:05:03.769000+00:00,0 days 00:00:59.545000,1278.344000,1279.120669
3,4,909782,39.784501,-105.085261,2022-03-09 12:07:21.803000+00:00,2022-03-09 12:07:21.803000+00:00,0 days 00:02:18.034000,1281.746995,1282.525451
4,5,909783,39.784735,-105.063591,2022-03-09 12:08:21.830000+00:00,2022-03-09 12:08:21.830000+00:00,0 days 00:01:00.027000,1283.202415,1283.981635
...,...,...,...,...,...,...,...,...,...
1613,1614,911392,39.786299,-104.811715,2022-03-12 22:01:34.597000+00:00,2022-03-12 22:01:34.597000+00:00,0 days 00:00:33.481000,1300.248459,1301.036677
1614,1615,911393,39.786206,-104.811759,2022-03-12 22:02:06.613000+00:00,2022-03-12 22:02:06.613000+00:00,0 days 00:00:32.016000,1300.251709,1301.039931
1615,1616,911394,39.785963,-104.811527,2022-03-12 22:02:42.434000+00:00,2022-03-12 22:02:42.434000+00:00,0 days 00:00:35.821000,1300.283733,1301.071976
1616,1617,911395,39.786378,-104.811420,2022-03-12 22:03:14.305000+00:00,2022-03-12 22:03:14.305000+00:00,0 days 00:00:31.871000,1300.263328,1301.051553
1617,1618,911396,39.785948,-104.811264,2022-03-12 22:03:50.655000+00:00,2022-03-12 22:03:50.655000+00:00,0 days 00:00:36.350000,1300.302705,1301.090958

In [ ]:
#Find minimum distance
print('The closest Prof WB came was: '+str(df['distance_phi'].min())+' km,')

#Find date and timestamp
print('@ approx: '+str(df['timestamp'][df['distance_phi'].idxmin()]))

#Find location @ time and place
loc = []

print('Location: '+str(df['lat'][df['distance_phi'].idxmin()])+', '+str(df['lon'][df['distance_phi'].idxmin()]))

The closest Prof WB came was: 0.19152968318673347 km,
@ approx: 2022-03-11 23:04:38.223000+00:00
Location: 46.0727016, -118.3285064

In [ ]:
#Hypothesis: I predict that 90% of the positions in this dataframe are with 3 km of Olin Hall

#Import plotly and math to do the map circle illustration
import plotly.express as px
import plotly.graph_objects as go
import math

#Save Olin Hall's coordinates
olin_hall_lat = 46.0728341
olin_hall_lon = -118.3290384
olin_hall_coords = (olin_hall_lat, olin_hall_lon)

# Radius for the circle (3 km)
radius_km = 3

#Write a function to take the coordinates and desired radius of the circle
def get_circle_points(lat, lon, radius_km, num_points=200):
    """Generates points for a circle of a given radius (in km) around a center (lat, lon)."""
    points = []
    # Earth's radius in kilometers
    R = 6371.0
    # Convert radius and center coordinates to radians
    lat_rad = math.radians(lat)
    lon_rad = math.radians(lon)

    #Iterate over the range of points to get their approx position in lat. long format
    for i in range(num_points):
        bearing = math.radians(i * (360 / num_points))  # Bearing from 0 to 360 degrees

        # Calculate new latitude
        new_lat_rad = math.asin(math.sin(lat_rad) * math.cos(radius_km / R) +
                                math.cos(lat_rad) * math.sin(radius_km / R) * math.cos(bearing))

        # Calculate new longitude
        new_lon_rad = lon_rad + math.atan2(math.sin(bearing) * math.sin(radius_km / R) * math.cos(lat_rad),
                                        math.cos(radius_km / R) - math.sin(lat_rad) * math.sin(new_lat_rad))

        points.append((math.degrees(new_lat_rad), math.degrees(new_lon_rad)))
    return points

# Build the points for the 30km circle around Olin Hall
circle_points = get_circle_points(olin_hall_lat, olin_hall_lon, radius_km)
circle_lats, circle_lons = zip(*circle_points)

# Create the Plotly map
fig = px.scatter_mapbox(df,
                        lat="lat",
                        lon="lon",
                        zoom=8,
                        mapbox_style="open-street-map",
                        title=f'Prof WB Location Data with {radius_km}km Radius around Olin Hall')

# Add the 30km radius circle around Olin Hall
fig.add_trace(go.Scattermapbox(
    lat=circle_lats,
    lon=circle_lons,
    mode="lines",
    line=dict(width=2, color="red"),
    name=f'{radius_km}km Radius around Olin Hall',
    hoverinfo='name'
))

# Add a marker for Olin Hall
fig.add_trace(go.Scattermapbox(
    lat=[olin_hall_lat],
    lon=[olin_hall_lon],
    mode="markers",
    marker=go.scattermapbox.Marker(size=10, color='green', symbol='star'),
    name="Olin Hall",
    hoverinfo='name'
))

fig.show()

In [ ]:
#Pie plot to visualize the results in context
#Define within & without 3 km of Olin hall
df['within_3km_olin'] = df['distance_Olin'] <= 3

proximity_counts = df['within_3km_olin'].value_counts().reset_index()
proximity_counts.columns = ['Within 3km of Olin Hall Label', 'Count']

# Create a new column with the desired hover titles
proximity_counts['Hover Title'] = proximity_counts['Within 3km of Olin Hall Label'].map({True: 'Within 3km of Olin Hall', False: 'Outside 3km of Olin Hall'})

fig_pie = px.pie(proximity_counts,
                 values='Count',
                 names='Hover Title',
                 title='Proportion of Locations Within 3km of Olin Hall',
                 labels={True: 'Within 30km', False: 'Outside 30km'})

fig_pie.show()